config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles do
      resources :comments
  end

  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'
end


# Rails.application.routes.draw do
#   devise_for :users, :controllers => { registrations: 'registrations' }
#   resources :articles do
#     resources :comments
#   end
#   resources :contacts
#   root to: 'pages#index'
#   get 'pages/contact'
#   get 'pages/about'
# end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :articles
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
    @last5 = Article.last(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    # @article = Article.new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(params[:comment].permit(:body))
        @comment.user_id = current_user.id if current_user

        if @comment.save
            redirect_to article_path(@article), notice: "Your comment has been saved."
        else
            redirect_to 'new'
        end
    end

    def update
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])

        if @comment.update(params[:comment].permit(:body))
            redirect_to article_path(@article), notice: "Your comment has been updated."
        else
            redirect_to 'edit'
        end
    end

    def edit
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), notice: "Your comment has beed deleted. "
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        if current_user
            redirect_to articles_path
        end
        @articles = Article.last(5)
    end

    def contact

    end

    def about

    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(
            :email,
            :password,
            :password_confirmation,
            :username,
            :firstname,
            :lastname
        )
    end

    def account_update_params
        params.require(:user).permit(
            :email,
            :password,
            :password_confirmation,
            :current_password,
            :username,
            :firstname,
            :lastname
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.haml
= simple_form_for(@article) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :body
  .form-actions
    = f.button :submit

app/views/articles/edit.haml
%h1 Editing Article
= render 'form'
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.haml
.row
  / Blog article Content Column
  .col-lg-8
    - @articles.each do |article|
      / Blog article
      / Title
      %h4{:style => "font-size: 45.5px;"}= link_to article.title, article
      / Date/Time
      %p
        %span.glyphicon.glyphicon-time
      / Author
      %p
        Article By:
        %strong
          = article.user.username
      %hr/
      / articleed Comments
      / Comment
    = link_to "New article", new_article_path, class: "btn btn-default btn-xs"
  / Blog Sidebar Widgets Column
  .col-md-4
    .well
      %h4 Recent articles
      - @last5.each do |a|
        Created by: #{a.user.username}
        %br/
        %strong= link_to a.title, a
        %p= truncate(a.body)
= will_paginate @articles
%br/

app/views/articles/new.haml
%h1 New Article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.haml
/ Index Page
.row
  / Blog Post Content Column
  .col-lg-8
    / Blog Post
    / Title
    %h1{ style: "font-size: 62.5px;" }
      = @article.title
    / Author
    %p.lead
      = @article.user.username
    %hr/
    / Date/Time
    %p
      %span.glyphicon.glyphicon-time
      Was Posted:
      = time_ago_in_words(@article.created_at)
    %hr/
    / Post Content
    = @article.body
    %hr/
    / Blog Comments
    = render @article.comments
    %hr/
    / Comments Form
    = render 'comments/form'
    %hr/
    / Posted Comments
    / Comment
  / Blog Sidebar Widgets Column
  .col-md-4
    / Blog Search Well
    / Blog Categories Well
    / Side Widget Well
    .well
      %h4 Recent Post
= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path
%br/
%br/

app/views/comments/_comment.haml
.media
  .pull-left
    = comment.user.username
  .media-body
    %p.media-heading.pull-right
      = time_ago_in_words(comment.created_at)
    %br/
    = comment.body
= link_to "Edit", edit_article_comment_path(comment.article, comment)
= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for ([@article, @article.comments.build]) do |f|
  .form-inputs
    = f.input :body
  .form-actions
    = f.button :submit, "Post your comment"
/ <h1>test form comment</h1>

app/views/comments/edit.haml
%h1 Edit Comment
= simple_form_for([@article, @comment]) do |f|
  = f.input :body
  = f.submit

app/views/layouts/_foot.haml
%footer.footer-distributed.navbar-fixed-bottom
  .footer-right
    %a{:href => "#"}
      %i.fa.fa-facebook
    %a{:href => "#"}
      %i.fa.fa-twitter
    %a{:href => "#"}
      %i.fa.fa-linkedin
    %a{:href => "#"}
      %i.fa.fa-github
  .footer-left
    %p.footer-links
      ·
      \#{link_to "Contact Us", pages_contact_path, class: "page-scroll"}
      ·
      \#{link_to "About Us", pages_about_path, class: "page-scroll"}
      ·
    %p

app/views/layouts/_nav.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Andre's Articles", root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Contact Us", pages_contact_path
        %li= link_to "About Us",  pages_about_path
        %li= link_to "View Articles", articles_path
        - if !current_user
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign in",  new_user_session_path
        - else
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.username
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li= link_to "Edit My Profile", edit_user_registration_path
              %li.divider{:role => "separator"}
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Steve's Articles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
 <%= bootstrap_flash %>
<div class='container'>
  <%= yield %>
</div>

<%= render 'layouts/foot' %>

</body>
</html>

app/views/pages/about.haml
about.haml

app/views/pages/contact.haml
contact.haml

app/views/pages/index.haml
.row
  .col-lg-8
    / Blog Post
    / Title
    .jumbotron
      %h1 Welcome to Andre's Articles.
      %p Awesome applications built with Rails!
      %p
  / Blog Sidebar Widgets Column
  .col-md-4
    / Blog Categories Well
    / Side Widget Well
    .well
      %h4 Recent Posts
      - @articles.each do |a|
        Created by: #{a.user.username}
        %br/
        %strong= link_to a.title, a
        %p= truncate(a.body)
/ /.row
%hr/